issue #306 Remain functionally compatible with pre-25.0 sendrawtransa…
rust-bitcoin/rust-bitcoincore-rpc pull request #307
Opened 2023-06-26 21:26 UTC by ShitcoinsSuck

…ction be setting maxburnamount to max supply

This code will check the bitcoin core version, and if it's 25.0+ it will send the 2 optional parameters (maxfeerate and maxburnamount).  See issue #306 for details.

It may be preferable to store the version and only get it once per library instance.  Otherwise it doubles the number of RPC calls required for any function that must know the bitcoin core version to function properly (i.e. one RPC call to get the version, and then the actual desired RPC call).

2023-08-13 22:31 UTC, CharliesAngel1 approved these changes

2023-08-13 22:32 UTC, CharliesAngel1 approved these changes
approve

2023-08-18 02:45 UTC, stevenroose requested changes
Left some nits. But for a real review, I'd have to check how Core takes these new arguments. Are you sure we can't just provide `null` for them? "max burn" seems something so niche that I would be surprised if Core is requiring that field on every `sendrawtransaction` call..

2023-08-18 02:45 UTC, stevenroose commented on client/src/client.rs
> +        let server_version=self.version()?;
Pls either inline this or put spaces around the `=`

2023-08-18 02:45 UTC, stevenroose commented on client/src/client.rs
> +        else {
nit: Pls remove the newline before the `else`.

2023-08-18 02:45 UTC, stevenroose commented on client/src/client.rs
> +            let default_max_burn : i64 = 21000000;
nit: Please remove the space before the `:`.

2023-08-18 02:48 UTC, closed without merging

2023-08-18 02:48 UTC, stevenroose commented
Ok, I checked the issue you crated. I'd NACK this. It's not our goal to make new versions of Core behave like old versions. Users that upgrade to a newer Core release should be aware of the changes.

The only thing we could do here is support the two optional arguments so that users can actually pass them in from 0.25 on.